version: '3'
services:
  core:
    image: core
    container_name: core-c1
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - my-django-postgres-network
    environment:
      DB_NAME: my_site
      DB_USER: docker_user
      DB_PASSWORD: diyorbek0906
      DB_HOST: my-postgres
      DB_PORT: 5432


networks:
  my-django-postgres-network:
    external: true
