# Generated by Django 5.1.1 on 2024-10-03 11:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=123)),
                ("body", ckeditor.fields.RichTextField()),
                ("is_active", models.BooleanField(default=True)),
                ("slug", models.CharField(blank=True, max_length=123, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=123)),
                ("body", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(upload_to="media/project-images/")),
                ("url", models.CharField(max_length=123)),
                ("is_active", models.BooleanField(default=True)),
                ("slug", models.CharField(blank=True, max_length=123, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
